FROM oven/bun:latest
RUN apt-get update && apt-get install -y postgresql-client && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY docker/prisma-package.json ./package.json
RUN bun install
COPY packages/db/prisma ./packages/db/prisma
CMD ["sleep", "infinity"]
